name: latest-release-action
description: Fetch the latest release version for the current repository, optionally filtering by tag prefix.
author: alessiovierti
branding:
  icon: tag
  color: purple

inputs:
  tag-prefix:
    description: 'Prefix to filter tags by. If not specified, all tags will be considered.'
    required: false
    default: ''
outputs:
  latest-release:
    description: Latest release version
    value: ${{ steps.fetch-latest-release-version.outputs.latest-release }}
  commit-sha:
    description: Latest release tag's commit sha
    value: ${{ steps.fetch-latest-release-version.outputs.commit-sha }}

runs:
  using: composite
  steps:
    - id: fetch-latest-release-version
      run: |
        set -o xtrace
        set -o pipefail
        git fetch --tags
        git fetch --prune --unshallow
        PREFIX=${{ inputs.tag-prefix }}
        LAST_TAG=$(git describe --abbrev=0 --tags --match "${PREFIX}*")
        if [[ -z "${LAST_TAG}" ]]
        then
          echo "ERROR: No matching tags found." >&2
          exit 1
        fi
        echo "latest-release=${LAST_TAG}" | tee -a ${GITHUB_OUTPUT}
        COMMIT_SHA=$(git rev-list -n 1 ${LAST_TAG})
        echo "commit-sha=${COMMIT_SHA}" | tee -a ${GITHUB_OUTPUT}
        echo The latest release version is "${LAST_TAG} (${COMMIT_SHA})".
      shell: bash
